let lessons = [
    {
        id: 1,
        lesson: "Spanish",
        location: "Barcelona",
        price: 30,
        image:"src/images/spanish.png",
        spaces: 10,
        availableInventory : 10,
    },
    {
        id: 2,
        lesson: "History",
        location: "Cambridge",
        price: 50,
        image: "src/images/history.png",
        spaces: 4,
        availableInventory : 4,
    },
    {
        id: 3,
        lesson: "Chemisty",
        location: "Tokyo",
        price: 15,
        image: "src/images/chemisty.png",
        spaces: 7,
        availableInventory : 7,
    },
    {
        id: 4,
        lesson: "Physics",
        location: "Oxford",
        price: 60,
        image: "src/images/physics.png",
        spaces: 2,
        availableInventory : 2,
    },
    {
        id: 5,
        lesson: "Artificial Intelligence",
        location: "Prague",
        price: 70,
        image: "src/images/artificial intelligence.png",
        spaces: 1,
        availableInventory : 1,
    },
    {
        id: 6,
        lesson: "Cooking",
        location: "Paris",
        price: 20,
        image: "src/images/cooking.png",
        spaces: 8,
        availableInventory : 8,
    },
    {
        id: 7,
        lesson: "Driving",
        location: "Hendon",
        price: 65,
        image: "src/images/driving.png",
        spaces: 0,
        availableInventory : 0,
    },
    {
        id: 8,
        lesson: "Psychology",
        location: "Liverpool",
        price: 35,
        image: "src/images/psychology.png",
        spaces: 2,
        availableInventory : 2,
    },
    {
        id: 9,
        lesson: "Astronomy",
        location: "Amsterdam",
        price: 25,
        image: "src/images/astronomy.png",
        spaces: 0,
        availableInventory : 0,
    },
    {
        id: 10,
        lesson: "Law",
        location: "Budapest",
        price: 80,
        image: "src/images/law.png",
        spaces: 4,
        availableInventory : 4,
    },


]
